language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install python-coveralls"
  - "pip install --upgrade setuptools"
script:
  - python setup.py flake8
  - python setup.py nosetests
after_success:
  - coveralls
